TechShare/Models/chat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TechShare.Models
{
    public class chat
    {
        public int Id { get; set; }

        [DisplayName("投稿時間")]
        [DataType(DataType.DateTime)]
        public DateTime Time{ get; set; }

        [DisplayName("テキスト")]
        [DataType(DataType.Text)]
        public string Text { get; set; }

        [DisplayName("ファイル")]
        [DataType(DataType.Upload)]
        public int File { get; set; }

        //chatからUser参照
        [DisplayName("ユーザー")]
        public virtual User User { get; set; }

        //chatからGroup参照
        [DisplayName("グループ")]
        public virtual Group Group { get; set; }
    }
}

TechShare/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechShare.Data;
using TechShare.Models;
using TechShare.Models.VM;

namespace TechShare.Controllers
{
    public class GroupsController : Controller
    {
        private TechShareContext db = new TechShareContext();

        public ActionResult Title()
        {
            return View();
        }

        public ActionResult LeftGroupList(int? groupId)
        
        {
            //Group＿Userから取得
            var groups = db.Group_User.Where(m => m.Group_Id == groupId);

            var users = groups.Select(e => e.Users).ToList();

             return View(users);
            //return View(db.Groups.ToList());

        }

        // GET: Groups
        public ActionResult Index(int? id)
        {
            chat_VM test = new chat_VM();
            
            if (id != null)
            {
                test.Groups.Id = (int)id;
            }

            return View(test);
        }

        public ActionResult Back()
        {
            return View();
        }

        public ActionResult input(int? GroupId, int? UserId)
        {
            chat chat = new chat();
            chat.User = db.Users.Where(e => e.Id == UserId).FirstOrDefault();
            chat.Group = db.Groups.Where(e => e.Id == GroupId).FirstOrDefault();

            return View("input", chat);
        }

        public ActionResult Admin()
        {

            return View("Users/Index");
        }

        public ActionResult GroupList()
        {
            //ここに書く
            return View(db.Groups.ToList());
        }

        public ActionResult GroupChat()
        {
            Group model = new Group();

            return View("Create",model);
        }

        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: Groups/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateChats(string id)
        {
            chat chats = new chat();
            chats.Text = "こんにちは";
            chats.Id = 1;
            db.chats.Add(chats);
            db.SaveChanges();
            return RedirectToAction("chats/Index");


            //var chats = db.chats.Where(e => e.Group.Id.ToString() == id).ToList();

            //return View("chats/Index", chats);
        }

       // POST: Groups/Create
       // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
       // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
       [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name,icon")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("GroupList");
            }

            return View(group);
        }

        public ActionResult Send(chat model)
        {

            chat chat = new chat();
            chat.Text = model.Text;
            chat.Time = DateTime.Now;

            chat.User = db.Users.Find(model.User.Id);
            chat.Group = db.Groups.Find(model.Group.Id);

            //chat.User = model.User; //model.Users;
            //chat.Group = model.Group;//model.Groups;

            db.chats.Add(chat);
            db.SaveChanges();
            return RedirectToAction("input");


        }

        // POST: Groups/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Send([Bind(Include = "Name,Group_Id,Text")] chat_VM model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        foreach (var item in model.Chats)
        //        {
        //            db.chats.Add(item);
        //            db.SaveChanges();
        //        }
        //        return RedirectToAction("Index");
        //    }

        //    return View(model);
        //}

        // GET: Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name,icon")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Find(id);
            db.Groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechShare/Controllers/chatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechShare.Data;
using TechShare.Models;
using TechShare.Models.VM;

namespace TechShare.Controllers
{
    public class chatsController : Controller
    {
        private TechShareContext db = new TechShareContext();

        // GET: chats
        public ActionResult Index(string id)
        {
            chat_VM model = new chat_VM();
            //model.Chats = db.chats.ToList();

            model.Chats = db.chats.Where(e => e.Group.Id.ToString() == id).ToList();

            return View(model);
        }

        // GET: chats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            chat chat = db.chats.Find(id);
            if (chat == null)
            {
                return HttpNotFound();
            }
            return View(chat);
        }

        // GET: chats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: chats/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Time,Text,File")] chat chat)
        {
            if (ModelState.IsValid)
            {
                db.chats.Add(chat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(chat);
        }

        // GET: chats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            chat chat = db.chats.Find(id);
            if (chat == null)
            {
                return HttpNotFound();
            }
            return View(chat);
        }

        // POST: chats/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Time,Text,File")] chat chat)
        {
            Group group = new Group();
            group.Id = 1;
            chat.Group = group;
            if (ModelState.IsValid)
            {
                db.Entry(chat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chat);
        }

        // GET: chats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            chat chat = db.chats.Find(id);
            if (chat == null)
            {
                return HttpNotFound();
            }
            return View(chat);
        }

        // POST: chats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            chat chat = db.chats.Find(id);
            db.chats.Remove(chat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechShare/Views/chats/Create.cshtml
@model TechShare.Models.chat

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("CreateChats", "Groups")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>chat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.File, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
}

TechShare/Views/chats/Delete.cshtml
@model TechShare.Models.chat

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>chat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.File)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TechShare/Views/chats/Details.cshtml
@model TechShare.Models.chat

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>chat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.File)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TechShare/Views/chats/Edit.cshtml
@model TechShare.Models.chat

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>chat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.File, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TechShare/Views/chats/Index.cshtml
@model TechShare.Models.VM.chat_VM

@{
    ViewBag.Title = "Index";
    Layout = null;
}

<h2>全社員グループ</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">

    @foreach (var item in Model.Chats)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            @*<td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>*@
        </tr>
    }

</table>

TechShare/Views/chats/Title.cshtml
@model IEnumerable<TechShare.Models.Group>


@{
    ViewBag.Title = "Title";
}

<h2>全社員グループ</h2>